### ISSUE TITLE
Support different ID column names in entities

### ISSUE THREAD

**Issue by ghost** [grimsa/hibernate-single-table-bulk-id-strategy#1]
I'd like to be able to use a single global temporary table with just two columns, one for the ID and one for the discriminator. But we have a code base where the ID column name is not uniform across all entities. Most use "id" but others have a prefix like "enti_id". We have several such variations on the ID column name, but we always use only one column.

I created a global temporary table with columns "id" and "entity_name". During bulk operations, inserting data in the temp table works fine, but reading from it fails because we are trying to read eg. "enti_id" column, which does not exist.

I'd like to avoid having to create a column in the temp table for each of the ID name variations if possible, as there are quite a few.
I am willing to provide a solution using an extra property "ID_COLUMN", and make the strategy read IDs from that column when the property is provided. Would this be an acceptable solution? I can see it would not work with multicolumn IDs, but those are not really supported right now either.

**Comment by grimsa** [comment]
Sure, could you create a pull request?

Also, in case you're not aware, Hibernate 5.2.8 added [some new in-memory bulk ID strategies](http://in.relation.to/2017/02/01/non-temporary-table-bulk-id-strategies/). Switching to one of those might be the right thing to do in the long run, assuming they cover your needs.

**Comment by ghost** [comment]
Yes, I'll create a Pull Request soon :)

The problem we are facing is not that we can't create temporary tables, it is that Hibernate is not creating all the temporary tables with the default strategy (Global) when using multi-tenancy with different schemas https://hibernate.atlassian.net/browse/HHH-11879 . As I understand using database tables should perform better than the in-memory strategies, so I'd rather stick with that.

**Comment by grimsa** [comment]
PR imported.
