### ISSUE TITLE
Add support for overridden table ID columns when deleting from many-to-many join tables.

### ISSUE THREAD

**Issue by ghost** [grimsa/hibernate-single-table-bulk-id-strategy#3]
I ran into an issue where bulk deletes from join tables don't work when using this MultiTableBulkIdStrategy. It seems we try to select from the global temporary table using the ID column name from the original table rather than the one configured for the SingleGlobalTemporaryTableBulkIdStrategy.

A fix should be as simple as overriding `org.hibernate.hql.spi.id.AbstractTableBasedBulkIdHandler.generateIdSubselect(Queryable, AbstractCollectionPersister, IdTableInfo)` in the same way as the other `generateIdSubselect` method.

I'd be more than happy to provide a Pull Request with the above fix and a test case.

**Comment by grimsa** [comment]
@mdiotude Not sure if you're aware, but Hibernate 5.2.8 added new Bulk Id strategies, relying on which would be a more future-proof solution.
Link: https://in.relation.to/2017/02/01/non-temporary-table-bulk-id-strategies/

But if you're still using this, a PR would be very welcome.

**Comment by ghost** [comment]
@grimsa I just created the PR.
I have looked into the new Bulk Id strategies, but I'm worried about hitting the SQL statement length limits in my application. We use Oracle in a multi tenant application and it seems Hibernate is not always creating the temporary tables properly [HHH-11879](https://hibernate.atlassian.net/browse/HHH-11879). The single table gives us the same performance while giving us control over what tables get created.

**Comment by grimsa** [comment]
@mdiotude Version 1.3 that includes this fix is released to Sonatype OSS Maven repo. Should sync to Maven central soon.

**Comment by ghost** [comment]
I have it now, Thanks!
